## Pandas

Pandas is an open-sourced BSD-licensed library, providing high performance easy to use data structures and data analysis tools for Python programming language.

Agenda:
- What is Data Frame?
- What is Data Series?
- Different operations in Pandas

In [2]:
# first step is to import Pandas
import pandas as pd
import numpy as np

In [28]:
df1 = pd.DataFrame(np.arange(0,20).reshape(4,5), index=['Row1', 'Row2', 'Row3', 'Row4'], columns = ['Col1', 'Col2', 'Col3', 'Col4', 'Col5'])
df1

      Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [9]:
df1.to_csv('test1.csv')

In [11]:
## Accessing the elements
## 1. .loc (only row index) , 2. .iloc (index loc) (both row and column index)

df1.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Col5    4
Name: Row1, dtype: int32

In [13]:
type(df1.loc['Row1'])

pandas.core.series.Series

In [17]:
df2 = pd.DataFrame(np.arange(0,20).reshape(4,5), index=['Row1', 'Row1', 'Row3', 'Row4'], columns = ['Col1', 'Col2', 'Col3', 'Col4', 'Col5'])
df2

      Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row1     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [19]:
df2.loc['Row1']

      Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row1     5     6     7     8     9

In [23]:
type(df2.loc['Row1'])

pandas.core.frame.DataFrame

Series is basically one row or one column. Suppose you need to take combination of two columns to get unique rows. In that case each combination of two rows will be generating data series.

In [30]:
df1

      Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [32]:
df1.iloc[0:2, 0:2]

      Col1  Col2
Row1     0     1
Row2     5     6

In [34]:
type(df1.iloc[0:2, 0:2])

pandas.core.frame.DataFrame

In [36]:
df1.iloc[0:2, 0:1]

      Col1
Row1     0
Row2     5

In [38]:
type(df1.iloc[0:2, 0:1]) # though have one col, but this is dataframe also

pandas.core.frame.DataFrame

In [40]:
df1.iloc[0:1, 0:2]

      Col1  Col2
Row1     0     1

In [42]:
type(df1.iloc[0:1, 0:2]) # though have one row, but this is dataframe also

pandas.core.frame.DataFrame

In [44]:
df1.iloc[0:1, 0]

Row1    0
Name: Col1, dtype: int32

In [46]:
type(df1.iloc[0:1, 0])

pandas.core.series.Series

In [48]:
df1.iloc[0, 0:2]

Col1    0
Col2    1
Name: Row1, dtype: int32

In [50]:
type(df1.iloc[0, 0:2]) # no row index is coming so series

pandas.core.series.Series

In [52]:
df1.iloc[1, 0:2]

Col1    5
Col2    6
Name: Row2, dtype: int32

In [54]:
type(df1.iloc[1, 0:2]) # no row index is coming so series

pandas.core.series.Series

In [62]:
# converting dataframes to arrays
df1.iloc[:,:].values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
df1.iloc[:,:].values.shape

(4, 5)

In [66]:
df1.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
Col5    0
dtype: int64

In [68]:
df1.isna().sum()

Col1    0
Col2    0
Col3    0
Col4    0
Col5    0
dtype: int64

In [72]:
df1['Col1'].value_counts()

Col1
0     1
5     1
10    1
15    1
Name: count, dtype: int64

In [74]:
df1['Col1'].unique()

array([ 0,  5, 10, 15])

In [76]:
df1['Col2'] # type = series

Row1     1
Row2     6
Row3    11
Row4    16
Name: Col2, dtype: int32

In [82]:
df1[['Col1', 'Col2']]

      Col1  Col2
Row1     0     1
Row2     5     6
Row3    10    11
Row4    15    16

In [100]:
## using csv data
df = pd.read_csv('../datasets/mercedesbenz_train.csv')
df

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [102]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [106]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [114]:
# get the unique category counts
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [116]:
# display all rows where y column is greater than 100
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [118]:
df.corr()

ValueError: could not convert string to float: 'k'

In [122]:
## CSV

from io import StringIO, BytesIO

In [140]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3\n')

type(data)

str

In [134]:
pd.read_csv(StringIO(data))

  col1  col2   col3
0    x     y      1
1    a     b      2
2    c     d      3

In [142]:
pd.read_csv(StringIO(data)).columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [144]:
df = pd.read_csv(StringIO(data), usecols = ['col1', 'col2'])
df

  col1 col2
0    x    y
1    a    b
2    c    d

In [146]:
pd.read_csv(StringIO(data), usecols = lambda x:x.upper() in ['COL1', 'COL2'])

  col1 col2
0    x    y
1    a    b
2    c    d

In [148]:
data1 = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11')

data1

'a,b,c,d\n1,2,3,4\n5,6,7,8\n9,10,11'

In [152]:
pd.read_csv(StringIO(data1))

   a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [154]:
pd.read_csv(StringIO(data1)).dtypes 
# as there is nan in col d, so it converted to float,  column type can't be int if there is null, it will be float

a      int64
b      int64
c      int64
d    float64
dtype: object

In [182]:
print(pd.read_csv(StringIO(data1), dtype=float))
print(pd.read_csv(StringIO(data1), dtype=float).dtypes)
print(pd.read_csv(StringIO(data1), dtype=float)['a'].dtype)

     a     b     c    d
0  1.0   2.0   3.0  4.0
1  5.0   6.0   7.0  8.0
2  9.0  10.0  11.0  NaN
a    float64
b    float64
c    float64
d    float64
dtype: object
float64

In [178]:
print(pd.read_csv(StringIO(data1), dtype=object))
print(pd.read_csv(StringIO(data1), dtype=object).dtypes)
print(type(pd.read_csv(StringIO(data1), dtype=str)['a'][1]))

   a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN
a    object
b    object
c    object
d    object
dtype: object
<class 'str'>

In [180]:
print(pd.read_csv(StringIO(data1), dtype=str))
print(pd.read_csv(StringIO(data1), dtype=str).dtypes)
print(type(pd.read_csv(StringIO(data1), dtype=str)['a'][1]))

   a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN
a    object
b    object
c    object
d    object
dtype: object
<class 'str'>

In [196]:
print(pd.read_csv(StringIO(data1), dtype={'a':'Int64', 'b': float, 'c':float}))
print(pd.read_csv(StringIO(data1), dtype={'a':'Int64', 'b': float, 'c':float}).dtypes)
print('\n')

print(pd.read_csv(StringIO(data1), dtype={'a':'Int64', 'b': int, 'c':float}))
print(pd.read_csv(StringIO(data1), dtype={'a':'Int64', 'b': int, 'c':float}).dtypes)
print(type(pd.read_csv(StringIO(data1), dtype={'a':'Int64', 'b': int, 'c':float})['a'][1]))
print(type(pd.read_csv(StringIO(data1), dtype={'a':'Int64', 'b': int, 'c':float})['b'][1]))

   a     b     c    d
0  1   2.0   3.0  4.0
1  5   6.0   7.0  8.0
2  9  10.0  11.0  NaN
a      Int64
b    float64
c    float64
d    float64
dtype: object


   a   b     c    d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN
a      Int64
b      int32
c    float64
d    float64
dtype: object
<class 'numpy.int64'>
<class 'numpy.int32'>

In [216]:
# set index
data_idx = ('index,a,b,c\n' '1,apple,bat,5.7\n' '2,orange,cow,10')
display(pd.read_csv(StringIO(data_idx)))
display(pd.read_csv(StringIO(data_idx), index_col = 0)) # make 0th col as index, col indexing starts from 0
display(pd.read_csv(StringIO(data_idx), index_col = 1)) # make 1st col as index, col indexing starts from 1

   index       a    b     c
0      1   apple  bat   5.7
1      2  orange  cow  10.0

            a    b     c
index
1       apple  bat   5.7
2      orange  cow  10.0

        index    b     c
a
apple       1  bat   5.7
orange      2  cow  10.0

In [236]:
data_idx1 = ('a,b,c,d\n' '1,apple,bat,5.7\n' '2,orange,cow,10')
data_idx1
display(pd.read_csv(StringIO(data_idx1))) # not making 1st column as index
display(pd.read_csv(StringIO(data_idx1), index_col = False)) # not making 1st column as index

   a       b    c     d
0  1   apple  bat   5.7
1  2  orange  cow  10.0

   a       b    c     d
0  1   apple  bat   5.7
1  2  orange  cow  10.0

In [242]:
# put comma after last item except 1st row
data_idx2 = ('a,b,c,d\n' '1,apple,bat,5.7,\n' '2,orange,cow,10,')
data_idx2
display(pd.read_csv(StringIO(data_idx2))) # making 1st column as index 
display(pd.read_csv(StringIO(data_idx2), index_col = False)) # not making 1st column as index

        a    b     c   d
1   apple  bat   5.7 NaN
2  orange  cow  10.0 NaN

   a       b    c     d
0  1   apple  bat   5.7
1  2  orange  cow  10.0

In [244]:
# put comma after last item in 1st row as well
data_idx2 = ('a,b,c,d,\n' '1,apple,bat,5.7,\n' '2,orange,cow,10,')
data_idx2
display(pd.read_csv(StringIO(data_idx2))) # making 1st column as index 
display(pd.read_csv(StringIO(data_idx2), index_col = False)) # not making 1st column as index

   a       b    c     d  Unnamed: 4
0  1   apple  bat   5.7         NaN
1  2  orange  cow  10.0         NaN

   a       b    c     d  Unnamed: 4
0  1   apple  bat   5.7         NaN
1  2  orange  cow  10.0         NaN

In [248]:
# quoting and escape characters, very useful in NLP

data = 'a,b"hello, \\"Bob\\", nice to see you",5'
pd.read_csv(StringIO(data), escapechar='\\')

Empty DataFrame
Columns: [a, b"hello,  "Bob",  nice to see you", 5]
Index: []

In [258]:
## Read JSON to CSV
# putting dictionary of title1 and title2 in list in title 
data = '{"employee_name" : "James", "email" : "james@gmail.com", "title" : [{"title1" : "Team Lead", "title2" : "Sr. Developper"}]}'
display(pd.read_json(data))
                    
# putting dictionary of title1 and title2 without list in title 
data = '{"employee_name" : "James", "email" : "james@gmail.com", "title" : {"title1" : "Team Lead", "title2" : "Sr. Developper"}}'
display(pd.read_json(data))

# putting dictionary of title1 and title2 without list in title 
data = '{"employee_name" : "James", "email" : {"email_primary" : "james@gmail.com", "email_secondary" : "james@gmail.com"}, "title" : {"title1" : "Team Lead", "title2" : "Sr. Developper"}}'
display(pd.read_json(data))

C:\Users\koyel\AppData\Local\Temp\ipykernel_3532\3179370355.py:4: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  display(pd.read_json(data))

,employee_name,email,title
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

C:\Users\koyel\AppData\Local\Temp\ipykernel_3532\3179370355.py:8: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  display(pd.read_json(data))

       employee_name            email           title
title1         James  james@gmail.com       Team Lead
title2         James  james@gmail.com  Sr. Developper

C:\Users\koyel\AppData\Local\Temp\ipykernel_3532\3179370355.py:12: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  display(pd.read_json(data))

                employee_name            email           title
email_primary           James  james@gmail.com             NaN
email_secondary         James  james@gmail.com             NaN
title1                  James              NaN       Team Lead
title2                  James              NaN  Sr. Developper

In [269]:
data = '{"employee_name" : "James", "email" : "james@gmail.com", "title" : [{"title1" : "Team Lead", "title2" : "Sr. Developper"}]}'
data_json = pd.read_json(data)
display(data_json)

display(data_json.to_json())
display(data_json.to_json(orient='index'))
display(data_json.to_json(orient='records'))

C:\Users\koyel\AppData\Local\Temp\ipykernel_3532\4043441081.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  data_json = pd.read_json(data)

,employee_name,email,title
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"title":{"0":{"title1":"Team Lead","title2":"Sr. Developper"}}}'

'{"0":{"employee_name":"James","email":"james@gmail.com","title":{"title1":"Team Lead","title2":"Sr. Developper"}}}'

'[{"employee_name":"James","email":"james@gmail.com","title":{"title1":"Team Lead","title2":"Sr. Developper"}}]'

In [271]:
data = '{"employee_name" : "James", "email" : "james@gmail.com", "title" : {"title1" : "Team Lead", "title2" : "Sr. Developper"}}'
data_json = pd.read_json(data)
display(data_json)

display(data_json.to_json())
display(data_json.to_json(orient='index'))
display(data_json.to_json(orient='records'))

C:\Users\koyel\AppData\Local\Temp\ipykernel_3532\1506244055.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  data_json = pd.read_json(data)

       employee_name            email           title
title1         James  james@gmail.com       Team Lead
title2         James  james@gmail.com  Sr. Developper

'{"employee_name":{"title1":"James","title2":"James"},"email":{"title1":"james@gmail.com","title2":"james@gmail.com"},"title":{"title1":"Team Lead","title2":"Sr. Developper"}}'

'{"title1":{"employee_name":"James","email":"james@gmail.com","title":"Team Lead"},"title2":{"employee_name":"James","email":"james@gmail.com","title":"Sr. Developper"}}'

'[{"employee_name":"James","email":"james@gmail.com","title":"Team Lead"},{"employee_name":"James","email":"james@gmail.com","title":"Sr. Developper"}]'

In [262]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [264]:
data.to_json(orient='index')

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"12":3.58,"13":1295},"8":{"0":1,"1":14.83,"2":1.64,"3":2.17,"4":14.0,"5":97,"6":2.8,"7":2.98,"8":0.29,"9":1.98,"10":5.2,"11":1.08,"12":2.85,"13":1045},"9":{"0":1,"1":13.86,"2":1.35,"3":2.27,"4":16.0,"5":98,"6":2.98,"7":3.15,"8":0.22,"9":1.85,"10":7.22,"11":1.01,"12":3.55,"13":1045},"10":{"0":1,"1":14.1,"2":2.16,"3":2.3,"4":18.0,"5":105,"6":2.95,"7":3.32,"8":0.22,"9":2.38,"10":5.75,"11":1.25,"12":3.17,"13":1510},"11":{"0":1,"1":14.12,"2":1.48,"3":2.32,"4":16.8,"5":95,"6":2.2,"7":2.43,"8":0.26,"9":1.57,"10":5.0,"11":1.17,"12":2.82,"13":1280},"12":{"0":1,"1":13.75,"2":1.73,"3":2.41,"4":16.0,"5":89,"6":2.6,"7":2.76,"8":0.29,"9":1.81,"10":5.6,"11":1.15,"12":2.9,"13":1320},"13":{"0":1,"1":14.75,"2":1.73,"3":2.39,"4":11.4,"5":91,"6":3.1,"7":3.69,"8":0.43,"9":2.81,"10":5.4,"11":1.25,"12":2.73,"13":1150},"14":{"0":1,"1":14.38,"2":1.87,"3":2.38,"4":12.0,"5":102,"6":3.3,"7":3.64,"8":0.29,"9":2.96,"10":7.5,"11":1.2,"12":3.0,"13":1547},"15":{"0":1,"1":13.63,"2":1.81,"3":2.7,"4":17.2,"5":112,"6":2.85,"7":2.91,"8":0.3,"9":1.46,"10":7.3,"11":1.28,"12":2.88,"13":1310},"16":{"0":1,"1":14.3,"2":1.92,"3":2.72,"4":20.0,"5":120,"6":2.8,"7":3.14,"8":0.33,"9":1.97,"10":6.2,"11":1.07,"12":2.65,"13":1280},"17":{"0":1,"1":13.83,"2":1.57,"3":2.62,"4":20.0,"5":115,"6":2.95,"7":3.4,"8":0.4,"9":1.72,"10":6.6,"11":1.13,"12":2.57,"13":1130},"18":{"0":1,"1":14.19,"2":1.59,"3":2.48,"4":16.5,"5":108,"6":3.3,"7":3.93,"8":0.32,"9":1.86,"10":8.7,"11":1.23,"12":2.82,"13":1680},"19":{"0":1,"1":13.64,"2":3.1,"3":2.56,"4":15.2,"5":116,"6":2.7,"7":3.03,"8":0.17,"9":1.66,"10":5.1,"11":0.96,"12":3.36,"13":845},"20":{"0":1,"1":14.06,"2":1.63,"3":2.28,"4":16.0,"5":126,"6":3.0,"7":3.17,"8":0.24,"9":2.1,"10":5.65,"11":1.09,"12":3.71,"13":780},"21":{"0":1,"1":12.93,"2":3.8,"3":2.65,"4":18.6,"5":102,"6":2.41,"7":2.41,"8":0.25,"9":1.98,"10":4.5,"11":1.03,"12":3.52,"13":770},"22":{"0":1,"1":13.71,"2":1.86,"3":2.36,"4":16.6,"5":101,"6":2.61,"7":2.88,"8":0.27,"9":1.69,"10":3.8,"11":1.11,"12":4.0,"13":1035},"23":{"0":1,"1":12.85,"2":1.6,"3":2.52,"4":17.8,"5":95,"6":2.48,"7":2.37,"8":0.26,"9":1.46,"10":3.93,"11":1.09,"12":3.63,"13":1015},"24":{"0":1,"1":13.5,"2":1.81,"3":2.61,"4":20.0,"5":96,"6":2.53,"7":2.61,"8":0.28,"9":1.66,"10":3.52,"11":1.12,"12":3.82,"13":845},"25":{"0":1,"1":13.05,"2":2.05,"3":3.22,"4":25.0,"5":124,"6":2.63,"7":2.68,"8":0.47,"9":1.92,"10":3.58,"11":1.13,"12":3.2,"13":830},"26":{"0":1,"1":13.39,"2":1.77,"3":2.62,"4":16.1,"5":93,"6":2.85,"7":2.94,"8":0.34,"9":1.45,"10":4.8,"11":0.92,"12":3.22,"13":1195},"27":{"0":1,"1":13.3,"2":1.72,"3":2.14,"4":17.0,"5":94,"6":2.4,"7":2.19,"8":0.27,"9":1.35,"10":3.95,"11":1.02,"12":2.77,"13":1285},"28":{"0":1,"1":13.87,"2":1.9,"3":2.8,"4":19.4,"5":107,"6":2.95,"7":2.97,"8":0.37,"9":1.76,"10":4.5,"11":1.25,"12":3.4,"13":915},"29":{"0":1,"1":14.02,"2":1.68,"3":2.21,"4":16.0,"5":96,"6":2.65,"7":2.33,"8":0.26,"9":1.98,"10":4.7,"11":1.04,"12":3.59,"13":1035},"30":{"0":1,"1":13.73,"2":1.5,"3":2.7,"4":22.5,"5":101,"6":3.0,"7":3.25,"8":0.29,"9":2.38,"10":5.7,"11":1.19,"12":2.71,"13":1285},"31":{"0":1,"1":13.58,"2":1.66,"3":2.36,"4":19.1,"5":106,"6":2.86,"7":3.19,"8":0.22,"9":1.95,"10":6.9,"11":1.09,"12":2.88,"13":1515},"32":{"0":1,"1":13.68,"2":1.83,"3":2.36,"4":17.2,"5":104,"6":2.42,"7":2.69,"8":0.42,"9":1.97,"10":3.84,"11":1.23,"12":2.87,"13":990},"33":{"0":1,"1":13.76,"2":1.53,"3":2.7,"4":19.5,"5":132,"6":2.95,"7":2.74,"8":0.5,"9":1.35,"10":5.4,"11":1.25,"12":3.0,"13":1235},"34":{"0":1,"1":13.51,"2":1.8,"3":2.65,"4":19.0,"5":110,"6":2.35,"7":2.53,"8":0.29,"9":1.54,"10":4.2,"11":1.1,"12":2.87,"13":1095},"35":{"0":1,"1":13.48,"2":1.81,"3":2.41,"4":20.5,"5":100,"6":2.7,"7":2.98,"8":0.26,"9":1.86,"10":5.1,"11":1.04,"12":3.47,"13":920},"36":{"0":1,"1":13.28,"2":1.64,"3":2.84,"4":15.5,"5":110,"6":2.6,"7":2.68,"8":0.34,"9":1.36,"10":4.6,"11":1.09,"12":2.78,"13":880},"37":{"0":1,"1":13.05,"2":1.65,"3":2.55,"4":18.0,"5":98,"6":2.45,"7":2.43,"8":0.29,"9":1.44,"10":4.25,"11":1.12,"12":2.51,"13":1105},"38":{"0":1,"1":13.07,"2":1.5,"3":2.1,"4":15.5,"5":98,"6":2.4,"7":2.64,"8":0.28,"9":1.37,"10":3.7,"11":1.18,"12":2.69,"13":1020},"39":{"0":1,"1":14.22,"2":3.99,"3":2.51,"4":13.2,"5":128,"6":3.0,"7":3.04,"8":0.2,"9":2.08,"10":5.1,"11":0.89,"12":3.53,"13":760},"40":{"0":1,"1":13.56,"2":1.71,"3":2.31,"4":16.2,"5":117,"6":3.15,"7":3.29,"8":0.34,"9":2.34,"10":6.13,"11":0.95,"12":3.38,"13":795},"41":{"0":1,"1":13.41,"2":3.84,"3":2.12,"4":18.8,"5":90,"6":2.45,"7":2.68,"8":0.27,"9":1.48,"10":4.28,"11":0.91,"12":3.0,"13":1035},"42":{"0":1,"1":13.88,"2":1.89,"3":2.59,"4":15.0,"5":101,"6":3.25,"7":3.56,"8":0.17,"9":1.7,"10":5.43,"11":0.88,"12":3.56,"13":1095},"43":{"0":1,"1":13.24,"2":3.98,"3":2.29,"4":17.5,"5":103,"6":2.64,"7":2.63,"8":0.32,"9":1.66,"10":4.36,"11":0.82,"12":3.0,"13":680},"44":{"0":1,"1":13.05,"2":1.77,"3":2.1,"4":17.0,"5":107,"6":3.0,"7":3.0,"8":0.28,"9":2.03,"10":5.04,"11":0.88,"12":3.35,"13":885},"45":{"0":1,"1":14.21,"2":4.04,"3":2.44,"4":18.9,"5":111,"6":2.85,"7":2.65,"8":0.3,"9":1.25,"10":5.24,"11":0.87,"12":3.33,"13":1080},"46":{"0":1,"1":14.38,"2":3.59,"3":2.28,"4":16.0,"5":102,"6":3.25,"7":3.17,"8":0.27,"9":2.19,"10":4.9,"11":1.04,"12":3.44,"13":1065},"47":{"0":1,"1":13.9,"2":1.68,"3":2.12,"4":16.0,"5":101,"6":3.1,"7":3.39,"8":0.21,"9":2.14,"10":6.1,"11":0.91,"12":3.33,"13":985},"48":{"0":1,"1":14.1,"2":2.02,"3":2.4,"4":18.8,"5":103,"6":2.75,"7":2.92,"8":0.32,"9":2.38,"10":6.2,"11":1.07,"12":2.75,"13":1060},"49":{"0":1,"1":13.94,"2":1.73,"3":2.27,"4":17.4,"5":108,"6":2.88,"7":3.54,"8":0.32,"9":2.08,"10":8.9,"11":1.12,"12":3.1,"13":1260},"50":{"0":1,"1":13.05,"2":1.73,"3":2.04,"4":12.4,"5":92,"6":2.72,"7":3.27,"8":0.17,"9":2.91,"10":7.2,"11":1.12,"12":2.91,"13":1150},"51":{"0":1,"1":13.83,"2":1.65,"3":2.6,"4":17.2,"5":94,"6":2.45,"7":2.99,"8":0.22,"9":2.29,"10":5.6,"11":1.24,"12":3.37,"13":1265},"52":{"0":1,"1":13.82,"2":1.75,"3":2.42,"4":14.0,"5":111,"6":3.88,"7":3.74,"8":0.32,"9":1.87,"10":7.05,"11":1.01,"12":3.26,"13":1190},"53":{"0":1,"1":13.77,"2":1.9,"3":2.68,"4":17.1,"5":115,"6":3.0,"7":2.79,"8":0.39,"9":1.68,"10":6.3,"11":1.13,"12":2.93,"13":1375},"54":{"0":1,"1":13.74,"2":1.67,"3":2.25,"4":16.4,"5":118,"6":2.6,"7":2.9,"8":0.21,"9":1.62,"10":5.85,"11":0.92,"12":3.2,"13":1060},"55":{"0":1,"1":13.56,"2":1.73,"3":2.46,"4":20.5,"5":116,"6":2.96,"7":2.78,"8":0.2,"9":2.45,"10":6.25,"11":0.98,"12":3.03,"13":1120},"56":{"0":1,"1":14.22,"2":1.7,"3":2.3,"4":16.3,"5":118,"6":3.2,"7":3.0,"8":0.26,"9":2.03,"10":6.38,"11":0.94,"12":3.31,"13":970},"57":{"0":1,"1":13.29,"2":1.97,"3":2.68,"4":16.8,"5":102,"6":3.0,"7":3.23,"8":0.31,"9":1.66,"10":6.0,"11":1.07,"12":2.84,"13":1270},"58":{"0":1,"1":13.72,"2":1.43,"3":2.5,"4":16.7,"5":108,"6":3.4,"7":3.67,"8":0.19,"9":2.04,"10":6.8,"11":0.89,"12":2.87,"13":1285},"59":{"0":2,"1":12.37,"2":0.94,"3":1.36,"4":10.6,"5":88,"6":1.98,"7":0.57,"8":0.28,"9":0.42,"10":1.95,"11":1.05,"12":1.82,"13":520},"60":{"0":2,"1":12.33,"2":1.1,"3":2.28,"4":16.0,"5":101,"6":2.05,"7":1.09,"8":0.63,"9":0.41,"10":3.27,"11":1.25,"12":1.67,"13":680},"61":{"0":2,"1":12.64,"2":1.36,"3":2.02,"4":16.8,"5":100,"6":2.02,"7":1.41,"8":0.53,"9":0.62,"10":5.75,"11":0.98,"12":1.59,"13":450},"62":{"0":2,"1":13.67,"2":1.25,"3":1.92,"4":18.0,"5":94,"6":2.1,"7":1.79,"8":0.32,"9":0.73,"10":3.8,"11":1.23,"12":2.46,"13":630},"63":{"0":2,"1":12.37,"2":1.13,"3":2.16,"4":19.0,"5":87,"6":3.5,"7":3.1,"8":0.19,"9":1.87,"10":4.45,"11":1.22,"12":2.87,"13":420},"64":{"0":2,"1":12.17,"2":1.45,"3":2.53,"4":19.0,"5":104,"6":1.89,"7":1.75,"8":0.45,"9":1.03,"10":2.95,"11":1.45,"12":2.23,"13":355},"65":{"0":2,"1":12.37,"2":1.21,"3":2.56,"4":18.1,"5":98,"6":2.42,"7":2.65,"8":0.37,"9":2.08,"10":4.6,"11":1.19,"12":2.3,"13":678},"66":{"0":2,"1":13.11,"2":1.01,"3":1.7,"4":15.0,"5":78,"6":2.98,"7":3.18,"8":0.26,"9":2.28,"10":5.3,"11":1.12,"12":3.18,"13":502},"67":{"0":2,"1":12.37,"2":1.17,"3":1.92,"4":19.6,"5":78,"6":2.11,"7":2.0,"8":0.27,"9":1.04,"10":4.68,"11":1.12,"12":3.48,"13":510},"68":{"0":2,"1":13.34,"2":0.94,"3":2.36,"4":17.0,"5":110,"6":2.53,"7":1.3,"8":0.55,"9":0.42,"10":3.17,"11":1.02,"12":1.93,"13":750},"69":{"0":2,"1":12.21,"2":1.19,"3":1.75,"4":16.8,"5":151,"6":1.85,"7":1.28,"8":0.14,"9":2.5,"10":2.85,"11":1.28,"12":3.07,"13":718},"70":{"0":2,"1":12.29,"2":1.61,"3":2.21,"4":20.4,"5":103,"6":1.1,"7":1.02,"8":0.37,"9":1.46,"10":3.05,"11":0.906,"12":1.82,"13":870},"71":{"0":2,"1":13.86,"2":1.51,"3":2.67,"4":25.0,"5":86,"6":2.95,"7":2.86,"8":0.21,"9":1.87,"10":3.38,"11":1.36,"12":3.16,"13":410},"72":{"0":2,"1":13.49,"2":1.66,"3":2.24,"4":24.0,"5":87,"6":1.88,"7":1.84,"8":0.27,"9":1.03,"10":3.74,"11":0.98,"12":2.78,"13":472},"73":{"0":2,"1":12.99,"2":1.67,"3":2.6,"4":30.0,"5":139,"6":3.3,"7":2.89,"8":0.21,"9":1.96,"10":3.35,"11":1.31,"12":3.5,"13":985},"74":{"0":2,"1":11.96,"2":1.09,"3":2.3,"4":21.0,"5":101,"6":3.38,"7":2.14,"8":0.13,"9":1.65,"10":3.21,"11":0.99,"12":3.13,"13":886},"75":{"0":2,"1":11.66,"2":1.88,"3":1.92,"4":16.0,"5":97,"6":1.61,"7":1.57,"8":0.34,"9":1.15,"10":3.8,"11":1.23,"12":2.14,"13":428},"76":{"0":2,"1":13.03,"2":0.9,"3":1.71,"4":16.0,"5":86,"6":1.95,"7":2.03,"8":0.24,"9":1.46,"10":4.6,"11":1.19,"12":2.48,"13":392},"77":{"0":2,"1":11.84,"2":2.89,"3":2.23,"4":18.0,"5":112,"6":1.72,"7":1.32,"8":0.43,"9":0.95,"10":2.65,"11":0.96,"12":2.52,"13":500},"78":{"0":2,"1":12.33,"2":0.99,"3":1.95,"4":14.8,"5":136,"6":1.9,"7":1.85,"8":0.35,"9":2.76,"10":3.4,"11":1.06,"12":2.31,"13":750},"79":{"0":2,"1":12.7,"2":3.87,"3":2.4,"4":23.0,"5":101,"6":2.83,"7":2.55,"8":0.43,"9":1.95,"10":2.57,"11":1.19,"12":3.13,"13":463},"80":{"0":2,"1":12.0,"2":0.92,"3":2.0,"4":19.0,"5":86,"6":2.42,"7":2.26,"8":0.3,"9":1.43,"10":2.5,"11":1.38,"12":3.12,"13":278},"81":{"0":2,"1":12.72,"2":1.81,"3":2.2,"4":18.8,"5":86,"6":2.2,"7":2.53,"8":0.26,"9":1.77,"10":3.9,"11":1.16,"12":3.14,"13":714},"82":{"0":2,"1":12.08,"2":1.13,"3":2.51,"4":24.0,"5":78,"6":2.0,"7":1.58,"8":0.4,"9":1.4,"10":2.2,"11":1.31,"12":2.72,"13":630},"83":{"0":2,"1":13.05,"2":3.86,"3":2.32,"4":22.5,"5":85,"6":1.65,"7":1.59,"8":0.61,"9":1.62,"10":4.8,"11":0.84,"12":2.01,"13":515},"84":{"0":2,"1":11.84,"2":0.89,"3":2.58,"4":18.0,"5":94,"6":2.2,"7":2.21,"8":0.22,"9":2.35,"10":3.05,"11":0.79,"12":3.08,"13":520},"85":{"0":2,"1":12.67,"2":0.98,"3":2.24,"4":18.0,"5":99,"6":2.2,"7":1.94,"8":0.3,"9":1.46,"10":2.62,"11":1.23,"12":3.16,"13":450},"86":{"0":2,"1":12.16,"2":1.61,"3":2.31,"4":22.8,"5":90,"6":1.78,"7":1.69,"8":0.43,"9":1.56,"10":2.45,"11":1.33,"12":2.26,"13":495},"87":{"0":2,"1":11.65,"2":1.67,"3":2.62,"4":26.0,"5":88,"6":1.92,"7":1.61,"8":0.4,"9":1.34,"10":2.6,"11":1.36,"12":3.21,"13":562},"88":{"0":2,"1":11.64,"2":2.06,"3":2.46,"4":21.6,"5":84,"6":1.95,"7":1.69,"8":0.48,"9":1.35,"10":2.8,"11":1.0,"12":2.75,"13":680},"89":{"0":2,"1":12.08,"2":1.33,"3":2.3,"4":23.6,"5":70,"6":2.2,"7":1.59,"8":0.42,"9":1.38,"10":1.74,"11":1.07,"12":3.21,"13":625},"90":{"0":2,"1":12.08,"2":1.83,"3":2.32,"4":18.5,"5":81,"6":1.6,"7":1.5,"8":0.52,"9":1.64,"10":2.4,"11":1.08,"12":2.27,"13":480},"91":{"0":2,"1":12.0,"2":1.51,"3":2.42,"4":22.0,"5":86,"6":1.45,"7":1.25,"8":0.5,"9":1.63,"10":3.6,"11":1.05,"12":2.65,"13":450},"92":{"0":2,"1":12.69,"2":1.53,"3":2.26,"4":20.7,"5":80,"6":1.38,"7":1.46,"8":0.58,"9":1.62,"10":3.05,"11":0.96,"12":2.06,"13":495},"93":{"0":2,"1":12.29,"2":2.83,"3":2.22,"4":18.0,"5":88,"6":2.45,"7":2.25,"8":0.25,"9":1.99,"10":2.15,"11":1.15,"12":3.3,"13":290},"94":{"0":2,"1":11.62,"2":1.99,"3":2.28,"4":18.0,"5":98,"6":3.02,"7":2.26,"8":0.17,"9":1.35,"10":3.25,"11":1.16,"12":2.96,"13":345},"95":{"0":2,"1":12.47,"2":1.52,"3":2.2,"4":19.0,"5":162,"6":2.5,"7":2.27,"8":0.32,"9":3.28,"10":2.6,"11":1.16,"12":2.63,"13":937},"96":{"0":2,"1":11.81,"2":2.12,"3":2.74,"4":21.5,"5":134,"6":1.6,"7":0.99,"8":0.14,"9":1.56,"10":2.5,"11":0.95,"12":2.26,"13":625},"97":{"0":2,"1":12.29,"2":1.41,"3":1.98,"4":16.0,"5":85,"6":2.55,"7":2.5,"8":0.29,"9":1.77,"10":2.9,"11":1.23,"12":2.74,"13":428},"98":{"0":2,"1":12.37,"2":1.07,"3":2.1,"4":18.5,"5":88,"6":3.52,"7":3.75,"8":0.24,"9":1.95,"10":4.5,"11":1.04,"12":2.77,"13":660},"99":{"0":2,"1":12.29,"2":3.17,"3":2.21,"4":18.0,"5":88,"6":2.85,"7":2.99,"8":0.45,"9":2.81,"10":2.3,"11":1.42,"12":2.83,"13":406},"100":{"0":2,"1":12.08,"2":2.08,"3":1.7,"4":17.5,"5":97,"6":2.23,"7":2.17,"8":0.26,"9":1.4,"10":3.3,"11":1.27,"12":2.96,"13":710},"101":{"0":2,"1":12.6,"2":1.34,"3":1.9,"4":18.5,"5":88,"6":1.45,"7":1.36,"8":0.29,"9":1.35,"10":2.45,"11":1.04,"12":2.77,"13":562},"102":{"0":2,"1":12.34,"2":2.45,"3":2.46,"4":21.0,"5":98,"6":2.56,"7":2.11,"8":0.34,"9":1.31,"10":2.8,"11":0.8,"12":3.38,"13":438},"103":{"0":2,"1":11.82,"2":1.72,"3":1.88,"4":19.5,"5":86,"6":2.5,"7":1.64,"8":0.37,"9":1.42,"10":2.06,"11":0.94,"12":2.44,"13":415},"104":{"0":2,"1":12.51,"2":1.73,"3":1.98,"4":20.5,"5":85,"6":2.2,"7":1.92,"8":0.32,"9":1.48,"10":2.94,"11":1.04,"12":3.57,"13":672},"105":{"0":2,"1":12.42,"2":2.55,"3":2.27,"4":22.0,"5":90,"6":1.68,"7":1.84,"8":0.66,"9":1.42,"10":2.7,"11":0.86,"12":3.3,"13":315},"106":{"0":2,"1":12.25,"2":1.73,"3":2.12,"4":19.0,"5":80,"6":1.65,"7":2.03,"8":0.37,"9":1.63,"10":3.4,"11":1.0,"12":3.17,"13":510},"107":{"0":2,"1":12.72,"2":1.75,"3":2.28,"4":22.5,"5":84,"6":1.38,"7":1.76,"8":0.48,"9":1.63,"10":3.3,"11":0.88,"12":2.42,"13":488},"108":{"0":2,"1":12.22,"2":1.29,"3":1.94,"4":19.0,"5":92,"6":2.36,"7":2.04,"8":0.39,"9":2.08,"10":2.7,"11":0.86,"12":3.02,"13":312},"109":{"0":2,"1":11.61,"2":1.35,"3":2.7,"4":20.0,"5":94,"6":2.74,"7":2.92,"8":0.29,"9":2.49,"10":2.65,"11":0.96,"12":3.26,"13":680},"110":{"0":2,"1":11.46,"2":3.74,"3":1.82,"4":19.5,"5":107,"6":3.18,"7":2.58,"8":0.24,"9":3.58,"10":2.9,"11":0.75,"12":2.81,"13":562},"111":{"0":2,"1":12.52,"2":2.43,"3":2.17,"4":21.0,"5":88,"6":2.55,"7":2.27,"8":0.26,"9":1.22,"10":2.0,"11":0.9,"12":2.78,"13":325},"112":{"0":2,"1":11.76,"2":2.68,"3":2.92,"4":20.0,"5":103,"6":1.75,"7":2.03,"8":0.6,"9":1.05,"10":3.8,"11":1.23,"12":2.5,"13":607},"113":{"0":2,"1":11.41,"2":0.74,"3":2.5,"4":21.0,"5":88,"6":2.48,"7":2.01,"8":0.42,"9":1.44,"10":3.08,"11":1.1,"12":2.31,"13":434},"114":{"0":2,"1":12.08,"2":1.39,"3":2.5,"4":22.5,"5":84,"6":2.56,"7":2.29,"8":0.43,"9":1.04,"10":2.9,"11":0.93,"12":3.19,"13":385},"115":{"0":2,"1":11.03,"2":1.51,"3":2.2,"4":21.5,"5":85,"6":2.46,"7":2.17,"8":0.52,"9":2.01,"10":1.9,"11":1.71,"12":2.87,"13":407},"116":{"0":2,"1":11.82,"2":1.47,"3":1.99,"4":20.8,"5":86,"6":1.98,"7":1.6,"8":0.3,"9":1.53,"10":1.95,"11":0.95,"12":3.33,"13":495},"117":{"0":2,"1":12.42,"2":1.61,"3":2.19,"4":22.5,"5":108,"6":2.0,"7":2.09,"8":0.34,"9":1.61,"10":2.06,"11":1.06,"12":2.96,"13":345},"118":{"0":2,"1":12.77,"2":3.43,"3":1.98,"4":16.0,"5":80,"6":1.63,"7":1.25,"8":0.43,"9":0.83,"10":3.4,"11":0.7,"12":2.12,"13":372},"119":{"0":2,"1":12.0,"2":3.43,"3":2.0,"4":19.0,"5":87,"6":2.0,"7":1.64,"8":0.37,"9":1.87,"10":1.28,"11":0.93,"12":3.05,"13":564},"120":{"0":2,"1":11.45,"2":2.4,"3":2.42,"4":20.0,"5":96,"6":2.9,"7":2.79,"8":0.32,"9":1.83,"10":3.25,"11":0.8,"12":3.39,"13":625},"121":{"0":2,"1":11.56,"2":2.05,"3":3.23,"4":28.5,"5":119,"6":3.18,"7":5.08,"8":0.47,"9":1.87,"10":6.0,"11":0.93,"12":3.69,"13":465},"122":{"0":2,"1":12.42,"2":4.43,"3":2.73,"4":26.5,"5":102,"6":2.2,"7":2.13,"8":0.43,"9":1.71,"10":2.08,"11":0.92,"12":3.12,"13":365},"123":{"0":2,"1":13.05,"2":5.8,"3":2.13,"4":21.5,"5":86,"6":2.62,"7":2.65,"8":0.3,"9":2.01,"10":2.6,"11":0.73,"12":3.1,"13":380},"124":{"0":2,"1":11.87,"2":4.31,"3":2.39,"4":21.0,"5":82,"6":2.86,"7":3.03,"8":0.21,"9":2.91,"10":2.8,"11":0.75,"12":3.64,"13":380},"125":{"0":2,"1":12.07,"2":2.16,"3":2.17,"4":21.0,"5":85,"6":2.6,"7":2.65,"8":0.37,"9":1.35,"10":2.76,"11":0.86,"12":3.28,"13":378},"126":{"0":2,"1":12.43,"2":1.53,"3":2.29,"4":21.5,"5":86,"6":2.74,"7":3.15,"8":0.39,"9":1.77,"10":3.94,"11":0.69,"12":2.84,"13":352},"127":{"0":2,"1":11.79,"2":2.13,"3":2.78,"4":28.5,"5":92,"6":2.13,"7":2.24,"8":0.58,"9":1.76,"10":3.0,"11":0.97,"12":2.44,"13":466},"128":{"0":2,"1":12.37,"2":1.63,"3":2.3,"4":24.5,"5":88,"6":2.22,"7":2.45,"8":0.4,"9":1.9,"10":2.12,"11":0.89,"12":2.78,"13":342},"129":{"0":2,"1":12.04,"2":4.3,"3":2.38,"4":22.0,"5":80,"6":2.1,"7":1.75,"8":0.42,"9":1.35,"10":2.6,"11":0.79,"12":2.57,"13":580},"130":{"0":3,"1":12.86,"2":1.35,"3":2.32,"4":18.0,"5":122,"6":1.51,"7":1.25,"8":0.21,"9":0.94,"10":4.1,"11":0.76,"12":1.29,"13":630},"131":{"0":3,"1":12.88,"2":2.99,"3":2.4,"4":20.0,"5":104,"6":1.3,"7":1.22,"8":0.24,"9":0.83,"10":5.4,"11":0.74,"12":1.42,"13":530},"132":{"0":3,"1":12.81,"2":2.31,"3":2.4,"4":24.0,"5":98,"6":1.15,"7":1.09,"8":0.27,"9":0.83,"10":5.7,"11":0.66,"12":1.36,"13":560},"133":{"0":3,"1":12.7,"2":3.55,"3":2.36,"4":21.5,"5":106,"6":1.7,"7":1.2,"8":0.17,"9":0.84,"10":5.0,"11":0.78,"12":1.29,"13":600},"134":{"0":3,"1":12.51,"2":1.24,"3":2.25,"4":17.5,"5":85,"6":2.0,"7":0.58,"8":0.6,"9":1.25,"10":5.45,"11":0.75,"12":1.51,"13":650},"135":{"0":3,"1":12.6,"2":2.46,"3":2.2,"4":18.5,"5":94,"6":1.62,"7":0.66,"8":0.63,"9":0.94,"10":7.1,"11":0.73,"12":1.58,"13":695},"136":{"0":3,"1":12.25,"2":4.72,"3":2.54,"4":21.0,"5":89,"6":1.38,"7":0.47,"8":0.53,"9":0.8,"10":3.85,"11":0.75,"12":1.27,"13":720},"137":{"0":3,"1":12.53,"2":5.51,"3":2.64,"4":25.0,"5":96,"6":1.79,"7":0.6,"8":0.63,"9":1.1,"10":5.0,"11":0.82,"12":1.69,"13":515},"138":{"0":3,"1":13.49,"2":3.59,"3":2.19,"4":19.5,"5":88,"6":1.62,"7":0.48,"8":0.58,"9":0.88,"10":5.7,"11":0.81,"12":1.82,"13":580},"139":{"0":3,"1":12.84,"2":2.96,"3":2.61,"4":24.0,"5":101,"6":2.32,"7":0.6,"8":0.53,"9":0.81,"10":4.92,"11":0.89,"12":2.15,"13":590},"140":{"0":3,"1":12.93,"2":2.81,"3":2.7,"4":21.0,"5":96,"6":1.54,"7":0.5,"8":0.53,"9":0.75,"10":4.6,"11":0.77,"12":2.31,"13":600},"141":{"0":3,"1":13.36,"2":2.56,"3":2.35,"4":20.0,"5":89,"6":1.4,"7":0.5,"8":0.37,"9":0.64,"10":5.6,"11":0.7,"12":2.47,"13":780},"142":{"0":3,"1":13.52,"2":3.17,"3":2.72,"4":23.5,"5":97,"6":1.55,"7":0.52,"8":0.5,"9":0.55,"10":4.35,"11":0.89,"12":2.06,"13":520},"143":{"0":3,"1":13.62,"2":4.95,"3":2.35,"4":20.0,"5":92,"6":2.0,"7":0.8,"8":0.47,"9":1.02,"10":4.4,"11":0.91,"12":2.05,"13":550},"144":{"0":3,"1":12.25,"2":3.88,"3":2.2,"4":18.5,"5":112,"6":1.38,"7":0.78,"8":0.29,"9":1.14,"10":8.21,"11":0.65,"12":2.0,"13":855},"145":{"0":3,"1":13.16,"2":3.57,"3":2.15,"4":21.0,"5":102,"6":1.5,"7":0.55,"8":0.43,"9":1.3,"10":4.0,"11":0.6,"12":1.68,"13":830},"146":{"0":3,"1":13.88,"2":5.04,"3":2.23,"4":20.0,"5":80,"6":0.98,"7":0.34,"8":0.4,"9":0.68,"10":4.9,"11":0.58,"12":1.33,"13":415},"147":{"0":3,"1":12.87,"2":4.61,"3":2.48,"4":21.5,"5":86,"6":1.7,"7":0.65,"8":0.47,"9":0.86,"10":7.65,"11":0.54,"12":1.86,"13":625},"148":{"0":3,"1":13.32,"2":3.24,"3":2.38,"4":21.5,"5":92,"6":1.93,"7":0.76,"8":0.45,"9":1.25,"10":8.42,"11":0.55,"12":1.62,"13":650},"149":{"0":3,"1":13.08,"2":3.9,"3":2.36,"4":21.5,"5":113,"6":1.41,"7":1.39,"8":0.34,"9":1.14,"10":9.4,"11":0.57,"12":1.33,"13":550},"150":{"0":3,"1":13.5,"2":3.12,"3":2.62,"4":24.0,"5":123,"6":1.4,"7":1.57,"8":0.22,"9":1.25,"10":8.6,"11":0.59,"12":1.3,"13":500},"151":{"0":3,"1":12.79,"2":2.67,"3":2.48,"4":22.0,"5":112,"6":1.48,"7":1.36,"8":0.24,"9":1.26,"10":10.8,"11":0.48,"12":1.47,"13":480},"152":{"0":3,"1":13.11,"2":1.9,"3":2.75,"4":25.5,"5":116,

In [273]:
## Read HTML data from URL
data_html = pd.read_html("https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/")
display(data_html)

[                             Bank NameBank       CityCity StateSt  CertCert  \
 0    Republic First Bank dba Republic Bank   Philadelphia      PA     27332
 1                            Citizens Bank       Sac City      IA      8758
 2                 Heartland Tri-State Bank        Elkhart      KS     25851
 3                      First Republic Bank  San Francisco      CA     59017
 4                           Signature Bank       New York      NY     57053
 ..                                     ...            ...     ...       ...
 564                     Superior Bank, FSB       Hinsdale      IL     32646
 565                    Malta National Bank          Malta      OH      6629
 566        First Alliance Bank & Trust Co.     Manchester      NH     34264
 567      National State Bank of Metropolis     Metropolis      IL      3815
 568                       Bank of Honolulu       Honolulu      HI     21029

                  Acquiring InstitutionAI Closing DateClosing  FundFund
 0      Fulton Bank, National Association      April 26, 2024     10546
 1              Iowa Trust & Savings Bank    November 3, 2023     10545
 2                 Dream First Bank, N.A.       July 28, 2023     10544
 3              JPMorgan Chase Bank, N.A.         May 1, 2023     10543
 4                    Flagstar Bank, N.A.      March 12, 2023     10540
 ..                                   ...                 ...       ...
 564                Superior Federal, FSB       July 27, 2001      6004
 565                    North Valley Bank         May 3, 2001      4648
 566  Southern New Hampshire Bank & Trust    February 2, 2001      4647
 567              Banterra Bank of Marion   December 14, 2000      4646
 568                   Bank of the Orient    October 13, 2000      4645

 [569 rows x 7 columns]]

In [275]:
type(data_html)

list

In [277]:
data_html[0]

,Bank NameBank,CityCity,StateSt,CertCert,Acquiring InstitutionAI,Closing DateClosing,FundFund
0,Republic First Bank dba Republic Bank,Philadelphia,PA,27332,"Fulton Bank, National Association","April 26, 2024",10546
1,Citizens Bank,Sac City,IA,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
2,Heartland Tri-State Bank,Elkhart,KS,25851,"Dream First Bank, N.A.","July 28, 2023",10544
3,First Republic Bank,San Francisco,CA,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
4,Signature Bank,New York,NY,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
...,...,...,...,...,...,...,...
564,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001",6004
565,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001",4648
566,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001",4647
567,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000",4646
568,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000",4645

In [279]:
type(data_html[0])

pandas.core.frame.DataFrame

In [285]:
## Read table from web page
# match parameter can be regex as well as specific string
url_mobile_country_code = "https://en.wikipedia.org/wiki/Mobile_country_code" 
df1 = pd.read_html(io = url_mobile_country_code, match = "Country") # will return tables containing string "Country", 
df1

[     Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns]]

In [293]:
df2= pd.read_html(io = url_mobile_country_code, match = "Brand") # will return tables containing string "Brand"
df2

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
 0    1    1  TEST  Test network  Operational         any
 1    1    1  TEST  Test network  Operational         any
 2  999   99   NaN  Internal use  Operational         any
 3  999  999   NaN  Internal use  Operational         any

                               References and notes
 0                                              NaN
 1                                              NaN
 2  Internal use in private networks, no roaming[6]
 3  Internal use in private networks, no roaming[6]  ,
      MCC  MNC     Brand                    Operator           Status  \
 0    901    1       NaN                     Webbing          Unknown
 1    901    2       NaN              GlobalmatiX AG          Unknown
 2    901    3   Iridium                         NaN      Operational
 3    901    4       NaN    BBIX Singapore Pte. Ltd.          Unknown
 4    901    5       NaN        Thuraya RMSS Network      Operational
 ..   ...  ...       ...                         ...              ...
 98   901   99       NaN  Athalos Global Services BV      Operational
 99   902    1       NaN          MulteFire Alliance      Operational
 100  991    1       NaN      World's Global Telecom  Not operational
 101  991    2  5G Croco                 Orange S.A.  Not operational
 102  991    3       NaN                   Halys SAS  Not operational

     Bands (MHz)                               References and notes
 0          MVNO            Former ICO Satellite Management[51][52]
 1       Unknown  Former Sense Communications International; veh...
 2     Satellite                                                NaN
 3       Unknown                              Former Globalstar[54]
 4     Satellite                                                NaN
 ..          ...                                                ...
 98         MVNO                                               [52]
 99          LTE                                           [6][121]
 100     Unknown  temporarily assigned until 15 January 2021[100...
 101          5G  temporarily assigned until 6 August 2022[123][...
 102     Unknown  temporary assignment for trial until 5 April 2...

 [103 rows x 7 columns],
    MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
 0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900

                                 References and notes
 0  There appears to be no officially assigned MCC...  ]

In [295]:
print(type(df1), len(df1))
print(type(df2), len(df2))

<class 'list'> 1
<class 'list'> 3

In [299]:
df3= pd.read_html(io = url_mobile_country_code) # returning all tables contained in that specifi webpage
print(type(df3), len(df3))
display(df3)

<class 'list'> 5

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
 0    1    1  TEST  Test network  Operational         any
 1    1    1  TEST  Test network  Operational         any
 2  999   99   NaN  Internal use  Operational         any
 3  999  999   NaN  Internal use  Operational         any

                               References and notes
 0                                              NaN
 1                                              NaN
 2  Internal use in private networks, no roaming[6]
 3  Internal use in private networks, no roaming[6]  ,
      Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns],
      MCC  MNC     Brand                    Operator           Status  \
 0    901    1       NaN                     Webbing          Unknown
 1    901    2       NaN              GlobalmatiX AG          Unknown
 2    901    3   Iridium                         NaN      Operational
 3    901    4       NaN    BBIX Singapore Pte. Ltd.          Unknown
 4    901    5       NaN        Thuraya RMSS Network      Operational
 ..   ...  ...       ...                         ...              ...
 98   901   99       NaN  Athalos Global Services BV      Operational
 99   902    1       NaN          MulteFire Alliance      Operational
 100  991    1       NaN      World's Global Telecom  Not operational
 101  991    2  5G Croco                 Orange S.A.  Not operational
 102  991    3       NaN                   Halys SAS  Not operational

     Bands (MHz)                               References and notes
 0          MVNO            Former ICO Satellite Management[51][52]
 1       Unknown  Former Sense Communications International; veh...
 2     Satellite                                                NaN
 3       Unknown                              Former Globalstar[54]
 4     Satellite                                                NaN
 ..          ...                                                ...
 98         MVNO                                               [52]
 99          LTE                                           [6][121]
 100     Unknown  temporarily assigned until 15 January 2021[100...
 101          5G  temporarily assigned until 6 August 2022[123][...
 102     Unknown  temporary assignment for trial until 5 April 2...

 [103 rows x 7 columns],
    MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
 0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900

                                 References and notes
 0  There appears to be no officially assigned MCC...  ,
                                vteTelecommunications  \
 0                                            History
 1                                           Pioneers
 2                                 Transmission media
 3                     Network topology and switching
 4                                       Multiplexing
 5                                           Concepts
 6                                   Types of network
 7                                   Notable networks
 8                                          Locations
 9  Telecommunication portal  Category  Outline  C...

                              vteTelecommunications.1
 0  Beacon Broadcasting Cable protection system Ca...
 1  Nasir Ahmed Edwin Howard Armstrong Mohamed M. ...
 2  Coaxial cable Fiber-optic communication optica...
 3  Bandwidth Links Nodes terminal Network switchi...
 4  Space-division Frequency-division Time-divisio...
 5  Communication protocol Computer network Data t...
 6  Cellular network Ethernet ISDN LAN Mobile NGN ...
 7  ARPANET BITNET CYCLADES FidoNet Internet Inter...
 8  Africa Americas North South Antarctica Asia Eu...
 9  Telecommunication portal  Category  Outline  C...  ]

In [303]:
## Read from excel file
data_excel = pd.read_excel("../datasets/excel_df_example.xlsx")
data_excel

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [306]:
## Pickling
## all pandas objects are equipped with to_pickle methods which use python's pickle modules to save data structures to disk using pickle format
data_excel.to_pickle('excel_to_pickle')
data_pickle = pd.read_pickle('excel_to_pickle')
data_pickle

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20