<a href="https://colab.research.google.com/github/Koyel1234/ai-ml-learning-journey/blob/main/google_colab_notebooks/nitish_singh/pytorch_notebooks/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!mv PyTorch.ipynb pytorch_notebooks_nitish_singh

mv: cannot stat 'PyTorch.ipynb': No such file or directory

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124

In [ ]:
if torch.cuda.is_available():
  print('GPU is available!')
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not availabe. Using CPU.")

GPU is available!
Using GPU: Tesla T4

# Creating a Tensor

In [ ]:
# using empty
torch.empty(2,3) # 2d tensor - matrix # allocates memory for (2,3) matrix # no new values assigned, whatever value will be at memory that will be shown

tensor([[0.0000e+00, 0.0000e+00, 3.1350e+32],
        [4.4184e-41, 3.1350e+32, 4.4184e-41]])

In [ ]:
# check type
a = torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3) # random numbers from 0-1

tensor([[0.9419, 0.7819, 0.8140],
        [0.5606, 0.8035, 0.5585]])

In [ ]:
torch.rand(2,3)

tensor([[0.3590, 0.9787, 0.3842],
        [0.7182, 0.9902, 0.5503]])

In [ ]:
# use manual_seed for reproducibility
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange -->", torch.arange(0,10,2))

# linspace
print("using linsapce -->", torch.linspace(0,10,10))

# using eye
print("using eye -->", torch.eye(5)) # identity matrix

# using full
print("using full -->", torch.full((3,3), 5))

using arange --> tensor([0, 2, 4, 6, 8])
using linsapce --> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye --> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full --> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # make tensor with same shape of x

tensor([[3180222411935070754, 8391722768137527840, 7959390389040738153],
        [2318285293787685492, 8675445202132104482, 7957695011165139568]])

In [ ]:
torch.zeros_like(x)  # create tensor of same shape as x with zeros

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x) # create tensor of same shape as x with ones

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.rand_like(x) ## create tensor of same shape as x with random numbers
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [ ]:
# find data types
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

# Mathematical Operations

## Scaler Operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition
print(x + 2)

# substraction
print(x - 2)

# multiplication
print(x*100)

# division
print(x/3)

# int division
print((x*100)//2)

# int division with int datatype
print(torch.tensor((x*100)//2, dtype=torch.int32))

# power
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[71.1765, 78.7581],
        [41.8305, 90.1415]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[35., 39.],
        [20., 45.]])
tensor([[35, 39],
        [20, 45]], dtype=torch.int32)
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

<ipython-input-25-d0b92d0ea3c5>:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(torch.tensor((x*100)//2, dtype=torch.int32))

## Elementwise Operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [ ]:
# add
print(a+b)

# sub
print(a-b)

# multiply
print(a*b)

# division
print(a/b)

# power
print(a**b)

# mod
print(a//b)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])
tensor([[1., 0., 0.],
        [0., 0., 1.]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction Operation

In [ ]:
e = torch.randint(size = (2,3), low=0, high=10)
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [ ]:
# sum
print(torch.sum(e))

# sum along columns
print(torch.sum(e, dim=0))

# sum along rows
print(torch.sum(e, dim=1))

tensor(24)
tensor([ 8,  0, 16])
tensor([15,  9])

In [ ]:
e = torch.randint(size = (2,3), low=0, high=10, dtype = torch.float32)
print(e)

# mean
print(torch.mean(e))

# mean along columns
print(torch.mean(e, dim=0))

# mean along rows
print(torch.mean(e, dim=1))

tensor([[5., 7., 3.],
        [9., 4., 0.]])
tensor(4.6667)
tensor([7.0000, 5.5000, 1.5000])
tensor([5.0000, 4.3333])

In [ ]:
# median
print(torch.median(e))

# median along columns
print(torch.median(e, dim=0))

# median along rows
print(torch.median(e, dim=1))

# is median function not doing mean for two middle values in case of even number of values?

tensor(4.)
torch.return_types.median(
values=tensor([5., 4., 0.]),
indices=tensor([0, 1, 1]))
torch.return_types.median(
values=tensor([5., 4.]),
indices=tensor([0, 1]))

In [ ]:
# max
print(torch.max(e))

# max along columns
print(torch.max(e, dim=0))

# max along rows
print(torch.max(e, dim=1))

tensor(9.)
torch.return_types.max(
values=tensor([9., 7., 3.]),
indices=tensor([1, 0, 0]))
torch.return_types.max(
values=tensor([7., 9.]),
indices=tensor([1, 0]))

In [ ]:
# min
print(torch.min(e))

# min along columns
print(torch.min(e, dim=0))

# min along rows
print(torch.min(e, dim=1))

tensor(0.)
torch.return_types.min(
values=tensor([5., 4., 0.]),
indices=tensor([0, 1, 1]))
torch.return_types.min(
values=tensor([3., 0.]),
indices=tensor([2, 2]))

In [ ]:
# product
print(torch.prod(e))

# min along columns
print(torch.prod(e, dim=0))

# min along rows
print(torch.prod(e, dim=1))

tensor(0.)
tensor([45., 28.,  0.])
tensor([105.,   0.])

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [ ]:
# variance
torch.var(e)

tensor(9.8667)

In [ ]:
# argmax
torch.argmax(e)

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(5)

## Matrix Operations

In [ ]:
f = torch.randint(size = (2,3), low = 0, high = 10)
g = torch.randint(size = (3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1],
        [5, 5],
        [0, 4]])

In [ ]:
# matrix multiplication
torch.matmul(f, g)

tensor([[42, 60],
        [82, 59]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [ ]:
# determinant # only for square matrix
torch.det(h)

tensor(-6.)

In [ ]:
# inverse # only for square matrix
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

## Comparison Operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])

In [ ]:
## final outcome will be all element wise true, false
# greater than
print(i>j)
# less than
print(i<j)
# equal to
print(i==j)
# not equal to
print(i!=j)
# greater than equal to
print(i>=j)

tensor([[False,  True, False],
        [ True, False, False]])
tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [ True, False, False]])

## Special Functions

In [ ]:
k = torch.randint(size=(2,3), low = 0, high = 10)
k

tensor([[5, 4, 4],
        [1, 1, 2]])

In [ ]:
# log
print(torch.log(k))
# exp
print(torch.exp(k))
# sqrt
print(torch.sqrt(k))
# sigmoid
print(torch.sigmoid(k))

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])
tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])
tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])
tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [ ]:
k = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
print(k)

# softmax
print(torch.softmax(k, dim=0))

tensor([[4., 7., 2.],
        [5., 6., 1.]])
tensor([[0.2689, 0.7311, 0.7311],
        [0.7311, 0.2689, 0.2689]])

In [ ]:
# relu
torch.relu(k)

tensor([[4., 7., 2.],
        [5., 6., 1.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])
tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [ ]:
m + n # creating new memory loc

tensor([[1.0769, 0.1227, 1.4047],
        [0.8966, 1.3610, 1.6774]])

In [ ]:
m.add_(n) # inplace operation

tensor([[1.0769, 0.1227, 1.4047],
        [0.8966, 1.3610, 1.6774]])

In [ ]:
m

tensor([[1.0769, 0.1227, 1.4047],
        [0.8966, 1.3610, 1.6774]])

In [ ]:
n

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [ ]:
torch.relu(n) # not inplace

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [ ]:
m.relu_() # inplace changes

tensor([[1.0769, 0.1227, 1.4047],
        [0.8966, 1.3610, 1.6774]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
b = a

In [ ]:
a[0][0] = 0
a

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
b # b also changed when we change a

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
id(a), id(b) # a and b got same memory, this is bcz of assignmnt operator which is not creating new memory loc, refering b towards memory loc of a

(135422629551408, 135422629551408)

In [ ]:
c = a.clone()
a

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
a[0][0] = 10
a

tensor([[10.0000,  0.4847,  0.9436],
        [ 0.3904,  0.2499,  0.3206]])

In [ ]:
c

tensor([[0.0000, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
id(a), id(c) # clone assigns new memory to c

(135422629551408, 135422629691120)

## Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')
device

device(type='cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving to an existing tensor
a = torch.rand(2,3)
a

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b = a.to(device)

In [ ]:
b

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]], device='cuda:0')

In [ ]:
b+5

tensor([[5.9753, 5.7582, 5.6688],
        [5.2651, 5.2336, 5.5057]], device='cuda:0')

In [ ]:
# difference in runtime for cpu and gpu
import time

# define the size of the matrices
size = 10000 # Large size for performance comparison


# create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on cpu: {cpu_time: .4f} seconds")


# move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # matrix multiplication on GPU
gpu_time = time.time() - start_time

print(f"Time on gpu: {gpu_time: .4f} seconds")

# Compare results
print("\nSpeedup (CPU time/ GPU time):", cpu_time/gpu_time)

Time on cpu:  15.6837 seconds
Time on gpu:  0.1138 seconds

Speedup (CPU time/ GPU time): 137.7819623991488

## Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.6423, 0.7098, 0.5644, 0.4549],
         [0.0729, 0.8535, 0.9793, 0.0611],
         [0.1162, 0.7666, 0.8801, 0.4203]],

        [[0.8186, 0.0463, 0.7306, 0.2009],
         [0.3265, 0.6684, 0.3509, 0.7772],
         [0.2353, 0.4301, 0.4385, 0.7375]]])

In [ ]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
# unsqueeze
c = torch.rand(226, 226, 3)
print(c.unsqueeze(0).shape)
print(c.unsqueeze(3).shape)

torch.Size([1, 226, 226, 3])
torch.Size([226, 226, 3, 1])

In [ ]:
# squeeze
d = torch.rand(1,20)
print(d, d.squeeze(0))
d.squeeze(0).shape

tensor([[0.3948, 0.2759, 0.8303, 0.0672, 0.3586, 0.7999, 0.6801, 0.0296, 0.6137,
         0.7967, 0.0059, 0.1704, 0.5136, 0.2683, 0.9056, 0.4449, 0.1763, 0.2762,
         0.3407, 0.6211]]) tensor([0.3948, 0.2759, 0.8303, 0.0672, 0.3586, 0.7999, 0.6801, 0.0296, 0.6137,
        0.7967, 0.0059, 0.1704, 0.5136, 0.2683, 0.9056, 0.4449, 0.1763, 0.2762,
        0.3407, 0.6211])

torch.Size([20])

In [ ]:
print(d, d.squeeze(1))
d.squeeze(1).shape

tensor([[0.3948, 0.2759, 0.8303, 0.0672, 0.3586, 0.7999, 0.6801, 0.0296, 0.6137,
         0.7967, 0.0059, 0.1704, 0.5136, 0.2683, 0.9056, 0.4449, 0.1763, 0.2762,
         0.3407, 0.6211]]) tensor([[0.3948, 0.2759, 0.8303, 0.0672, 0.3586, 0.7999, 0.6801, 0.0296, 0.6137,
         0.7967, 0.0059, 0.1704, 0.5136, 0.2683, 0.9056, 0.4449, 0.1763, 0.2762,
         0.3407, 0.6211]])

torch.Size([1, 20])

In [ ]:
d = torch.rand(2,20)
print(d[0])
print(d, d.squeeze(0))
d.squeeze(0).shape

tensor([0.5325, 0.4479, 0.2774, 0.2978, 0.5847, 0.0670, 0.3729, 0.3551, 0.1116,
        0.0189, 0.6903, 0.3864, 0.0882, 0.2219, 0.5777, 0.2853, 0.5694, 0.4612,
        0.0922, 0.6612])
tensor([[0.5325, 0.4479, 0.2774, 0.2978, 0.5847, 0.0670, 0.3729, 0.3551, 0.1116,
         0.0189, 0.6903, 0.3864, 0.0882, 0.2219, 0.5777, 0.2853, 0.5694, 0.4612,
         0.0922, 0.6612],
        [0.9396, 0.2164, 0.3324, 0.5327, 0.8959, 0.8782, 0.9930, 0.0288, 0.9703,
         0.6106, 0.6345, 0.6883, 0.7586, 0.0409, 0.9842, 0.8264, 0.2714, 0.7361,
         0.8367, 0.2349]]) tensor([[0.5325, 0.4479, 0.2774, 0.2978, 0.5847, 0.0670, 0.3729, 0.3551, 0.1116,
         0.0189, 0.6903, 0.3864, 0.0882, 0.2219, 0.5777, 0.2853, 0.5694, 0.4612,
         0.0922, 0.6612],
        [0.9396, 0.2164, 0.3324, 0.5327, 0.8959, 0.8782, 0.9930, 0.0288, 0.9703,
         0.6106, 0.6345, 0.6883, 0.7586, 0.0409, 0.9842, 0.8264, 0.2714, 0.7361,
         0.8367, 0.2349]])

torch.Size([2, 20])

# NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])

# Autograd

In [ ]:
def dy_dx(x):
  return 2*x

dy_dx(3)

6

In [ ]:
x = torch.tensor(2.0, requires_grad=True)

In [ ]:
y = x**2
x, y

(tensor(2., requires_grad=True), tensor(4., grad_fn=<PowBackward0>))

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.)

In [ ]:
import math
def dz_dx(x):
  return 2*x*math.cos(x**2)

dz_dx(3)

-5.466781571308061

In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2
z = torch.sin(y)

In [ ]:
y, z

(tensor(9., grad_fn=<PowBackward0>), tensor(0.4121, grad_fn=<SinBackward0>))

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

In [ ]:
y.grad

<ipython-input-128-10b3a7061f6d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

# Implement Neural Network

## Without Autograd

In [ ]:
import torch

# inputs
x = torch.tensor(6.7) # input feature
y = torch.tensor(0.0) # True label (binary)

w = torch.tensor(1.0) # Weight
b = torch.tensor(0.0) # bias

In [ ]:
# Binary Cross Entropy Loss for Scaler
def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8 # To prevent log(0)
  prediction = torch.clamp(prediction, epsilon, 1-epsilon)
  return -(target*torch.log(prediction) + (1-target)*torch.log(1-prediction))

In [ ]:
# Forward Pass
z = w*x + b # Weighted sum (linear part)
y_pred = torch.sigmoid(z) # Predicted probability

# Compute binary cross-binary loss
loss = binary_cross_entropy_loss(y_pred, y)

In [ ]:
loss

tensor(6.7012)

In [ ]:
# derivatives
# 1. dL/d(y_pred) : Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x # dz/dw = x
dz_db = 1 # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [ ]:
print(f"Manual gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual gradient of loss w.r.t bias (dw): {dL_db}")

Manual gradient of loss w.r.t weight (dw): 6.691762447357178
Manual gradient of loss w.r.t bias (dw): 0.998770534992218

## With Autograd

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)

## Working with Vector

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

## Clearing Gradients

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward() # after x.grad if you will again run this run without last line - fwd pass, error will appear

In [ ]:
x.grad

tensor(8.)

In [ ]:
x.grad.zero_()

tensor(0.)

## Deactivate Gradient Tracking

In [ ]:
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [ ]:
x.requires_grad_(False)
x

tensor(2.)

In [ ]:
y = x ** 2
y

tensor(4.)

In [ ]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
z = x.detach()
z

tensor(2.)

In [ ]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y1 = z**2
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
y.backward()

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
with torch.no_grad():
  y = x ** 2

In [ ]:
y

tensor(4.)

In [ ]:
y.backward() # will work without 'with' statement

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

# Making Neural Network by PyTorch

## Plan of Attack
1. We will build a simple neural network
2. train it on a real world dataset
3. Will mimic the PyTorch workflow
4. Will have a lot of manual elements
5. End result is not important

## Code Flow
1. Load the dataset
2. Basic Preprocessing
3. training Process\
  a. Create the model\
  b. Forward pass\
  c. Loss Calculation\
  d. Backprop\
  e. Parameters update
  
4. Model Evaluation

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns= ['id', 'Unnamed: 32'], inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.23346321, -0.56268004,  0.16987866, ..., -0.44873415,
        -0.78664824, -1.05468123],
       [ 0.87035109,  1.19467784,  0.91517036, ...,  1.15715615,
         0.69558106,  2.74638059],
       [-0.24920071, -1.31251702, -0.26245685, ..., -0.34356019,
        -0.24528396, -0.5676736 ],
       ...,
       [ 1.10739905, -0.5858948 ,  1.05195916, ...,  0.60071248,
        -0.07243874, -0.07356832],
       [-0.68616863,  0.18715694, -0.6641185 , ..., -0.53678678,
         0.45914185, -0.20350982],
       [-0.51195266, -0.19356524, -0.54349565, ..., -0.45530753,
         0.15747802, -0.64137991]])

In [ ]:
y_train

169    B
72     M
384    B
154    B
494    B
      ..
276    B
215    M
444    M
160    B
107    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0])

### NumPy arrays to PyTorch Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
X_train_tensor # dtype = float64

tensor([[ 0.2335, -0.5627,  0.1699,  ..., -0.4487, -0.7866, -1.0547],
        [ 0.8704,  1.1947,  0.9152,  ...,  1.1572,  0.6956,  2.7464],
        [-0.2492, -1.3125, -0.2625,  ..., -0.3436, -0.2453, -0.5677],
        ...,
        [ 1.1074, -0.5859,  1.0520,  ...,  0.6007, -0.0724, -0.0736],
        [-0.6862,  0.1872, -0.6641,  ..., -0.5368,  0.4591, -0.2035],
        [-0.5120, -0.1936, -0.5435,  ..., -0.4553,  0.1575, -0.6414]],
       dtype=torch.float64)

### Define the model

In [ ]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss
    loss = -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

In [ ]:
# using NN module
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  # def loss_function(self, y_pred, y):
  #   #clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

  #   #calculate loss
  #   loss = -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
  #   return loss

### Important Parameter

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# for NN module usecase
loss_function = nn.BCELoss()

### Training Pipeline

In [ ]:
# create model without NN module
model = MySimpleNN(X_train_tensor)
model.weights

tensor([[0.0937],
        [0.1496],
        [0.8998],
        [0.3723],
        [0.9663],
        [0.7534],
        [0.6538],
        [0.6412],
        [0.3524],
        [0.9888],
        [0.5100],
        [0.0931],
        [0.9373],
        [0.7255],
        [0.9324],
        [0.8068],
        [0.6842],
        [0.2970],
        [0.5045],
        [0.5711],
        [0.8829],
        [0.9119],
        [0.1613],
        [0.9187],
        [0.4501],
        [0.6466],
        [0.8609],
        [0.8816],
        [0.0551],
        [0.8417]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
# define loop without NN module
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.0536290368653474
Epoch: 2, Loss: 0.9833296169421898
Epoch: 3, Loss: 0.9284022015327881
Epoch: 4, Loss: 0.8864417219793764
Epoch: 5, Loss: 0.8546903089118074
Epoch: 6, Loss: 0.8305403228043953
Epoch: 7, Loss: 0.8118506453171662
Epoch: 8, Loss: 0.7970323531739766
Epoch: 9, Loss: 0.7849801118361754
Epoch: 10, Loss: 0.7749487009527514
Epoch: 11, Loss: 0.7664374795114429
Epoch: 12, Loss: 0.7591044128819993
Epoch: 13, Loss: 0.752708861534351
Epoch: 14, Loss: 0.7470755710724085
Epoch: 15, Loss: 0.7420725308096315
Epoch: 16, Loss: 0.7375973791000512
Epoch: 17, Loss: 0.7335689186405879
Epoch: 18, Loss: 0.7299216512675862
Epoch: 19, Loss: 0.7266021044915987
Epoch: 20, Loss: 0.7235662434140417
Epoch: 21, Loss: 0.7207775649570941
Epoch: 22, Loss: 0.7182056430064557
Epoch: 23, Loss: 0.7158249884630589
Epoch: 24, Loss: 0.7136141407823413
Epoch: 25, Loss: 0.7115549367353933

In [ ]:
model.weights

tensor([[-0.3472],
        [-0.2792],
        [ 0.4188],
        [-0.1032],
        [ 0.2448],
        [-0.0971],
        [-0.1678],
        [-0.1372],
        [-0.1405],
        [ 0.3504],
        [-0.1421],
        [-0.1882],
        [ 0.2853],
        [ 0.1512],
        [ 0.3958],
        [ 0.0776],
        [-0.0214],
        [-0.4106],
        [ 0.2095],
        [-0.1346],
        [ 0.3481],
        [ 0.4741],
        [-0.4050],
        [ 0.3608],
        [-0.2485],
        [-0.0706],
        [ 0.1248],
        [ 0.1503],
        [-0.3181],
        [ 0.1324]], dtype=torch.float64, requires_grad=True)

In [ ]:
X_train_tensor.shape[1]

30

In [ ]:
X_train_tensor.dtype

torch.float64

In [ ]:
# with NN module

model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim(SGD(mode.parameters(), lr = learning_rate))


# features = torch.rand(30,1)
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # loss calculate (without nn loss func)
  # loss = model.loss_function(y_pred, y_train_tensor)
  # print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

  # loss calculate (with nn loss func)
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))


  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  # parameters update
  optimizer.step()

  # # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

# Evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred>0.7).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

# print(y_pred, y_train_tensor)

Accuracy: 0.602031409740448

# NN Module

In [ ]:
# create model
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
# create datasts
features = torch.rand(10,5)
print(features.shape[1])
# create model
model = Model(features.shape[1])

# call model for forwardpass
# model.forward(features)
model(features)

5

tensor([[0.5777],
        [0.5806],
        [0.5824],
        [0.5880],
        [0.5783],
        [0.5761],
        [0.5879],
        [0.6001],
        [0.5911],
        [0.5839]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.3842, -0.4099,  0.0964, -0.3605, -0.0636]], requires_grad=True)

In [ ]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.1814], requires_grad=True)

In [ ]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
# create datasts
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forwardpass
# model.forward(features)
model(features)

tensor([[0.4305],
        [0.3838],
        [0.3979],
        [0.3712],
        [0.3969],
        [0.4695],
        [0.4555],
        [0.4828],
        [0.4490],
        [0.3758]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[-0.3015,  0.2128, -0.0030,  0.0326,  0.0703],
        [ 0.0212,  0.4031, -0.4435, -0.0482, -0.2458],
        [-0.3151,  0.3973, -0.3265,  0.0936,  0.3599]], requires_grad=True)

In [ ]:
# show model weights
model.linear2.weight

Parameter containing:
tensor([[-0.5232, -0.1178, -0.3705]], requires_grad=True)

In [ ]:
# show model bias
model.linear1.bias

Parameter containing:
tensor([0.0421, 0.1502, 0.4385], requires_grad=True)

In [ ]:
# show model bias
model.linear2.bias

Parameter containing:
tensor([-0.0473], requires_grad=True)

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [ ]:
# create datasts
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forwardpass
# model.forward(features)
model(features)

tensor([[0.4068],
        [0.4026],
        [0.4053],
        [0.4083],
        [0.4024],
        [0.4045],
        [0.4054],
        [0.4079],
        [0.4045],
        [0.4043]], grad_fn=<SigmoidBackward0>)